### ISSUE TITLE
Fix namespaces for all XSL (in ISO/TEI conversion)

### ISSUE THREAD

**Issue by hannahedeland** [EXMARaLDA/exmaralda#281]
Namespaces appear explicitly in results even though they shouldn't and I don't know why...

**Comment by Herrner** [comment]
as a general hint: because they suck. oh, never mind...

**Comment by berndmoos** [comment]
@hannahedeland : Is this an issue? I don't think we need to worry as long as everything is well-formed and valid

**Comment by hannahedeland** [comment]
I'm not worried, I was hoping for someone to tell me why this happens and how we can get it right, but if that's not going to happen, then we can just forget about it and agree that namespaces suck :)

**Comment by berndmoos** [comment]
We forget about it.

**Comment by hannahedeland** [comment]
Still clueless about XSL, but I got it to behave in Java using the namespace of the root element of the document I got from the SAXBuilder, i.e. `Namespace TEI = teiDocument.getRootElement().getNamespace();` instead of `Namespace TEI = Namespace.getNamespace("tei", "http://www.tei-c.org/ns/1.0");`, which will however not work for XPath, because `Namespace: prefix "" is mapped to URI "http://www.tei-c.org/ns/1.0"` and we need prefix "tei" I guess. I still feel stupid, but the files look better, maybe I can remember this and somehow use it for the XSL too...
