### ISSUE TITLE
Check/fix whitespace handling for all XSL (in ISO/TEI conversion)

### ISSUE THREAD

**Issue by hannahedeland** [EXMARaLDA/exmaralda#282]
Things should not get messed up if the XML has been pretty-printed for whatever reasons, when someone has too much free time, that someone should look into this...

**Comment by berndmoos** [comment]
The solution is: do notte pretty prynte unleth thou hast with a schema athothiated thy XML.

**Comment by berndmoos** [comment]
@hannahedeland : status?

**Comment by hannahedeland** [comment]
Nobody had too much free time? :/

**Comment by berndmoos** [comment]
@hannahedeland and @berndmoos decided: this is not an issue

**Comment by berndmoos** [comment]
It is an issue because current white space handling makes roundtrips ugly. Did two things: 

1. do not pretty print TEI exports (issue #340)
2. do not copy whitespace in XSL "Detokenize". 

Not sure if that is it.

**Comment by berndmoos** [comment]
Any problems with this found during roundtripping (#367) were wiped from the face of the earth.
