### ISSUE TITLE
Rename CLARIN menu to "Web services"

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#285]
'tis more apt, and there may be others

**Comment by berndmoos** [comment]
Holy crap, that was easy!

**Comment by hannahedeland** [comment]
maybe rename the package too?

**Comment by berndmoos** [comment]
Renamed the menu class and the package containing the actions. 'most nuthin' ain't called CLARIN no' mo'. Anything else?

**Comment by berndmoos** [comment]
Done
