### ISSUE TITLE
augmentTimeline.xsl fails in overlaps

### ISSUE THREAD

**Issue by hannahedeland** [EXMARaLDA/exmaralda#288]
token annotation in ISO/TEI gets messed up by augmentTimeline.xsl when there are `<anchor>`s in the `<seg>`s (i.e. overlaps) since not enough new token `<anchor>`s are created for each token, maybe avoiding those UNSOLVABLE TIME PROBLEMs too strictly

**Comment by berndmoos** [comment]
@hannahedeland : this is *not* resolved, or is it?

**Comment by hannahedeland** [comment]
I thought your new approach would solve exactly this problem, but I can have a look.

**Comment by hannahedeland** [comment]
I tried to test this, but running P-E with augmentTimeline2.xsl fails (`Line#: 101; Column#: -1 ValidationException: Cannot convert string "" to a double`) when I try to import the HIAT ISO/TEI export of AnneWill, but this doesn't happen when I go through each step without the P-E (and I don't know why, maybe different processing?), but the resulting timeline has `@this` and `@next` on the `<when>` so somethings weird is going on there, do you want to have a look or should I?

**Comment by berndmoos** [comment]
Trying to close this. It will reopen, I'm sure.
