### ISSUE TITLE
DeepL translation as web service

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#297]
See https://www.deepl.com/de/docs-api/

You select a tier, you choose whether to send individual events or whole segment chains to DeepL, you pick a target language and a target tier and you get a tier with translations back. Yes, that's what you do. Technology is a miraculous thing.

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/143782428-e58e1948-cdf5-4d0f-8da3-79a6bb84e85c.png)

**Comment by berndmoos** [comment]
It's there. To do: segmentation

**Comment by berndmoos** [comment]
Segmentation is there

**Comment by sarkipo** [comment]
Wanted to play with DeepL, got a free DeepL account and an API key (ending in ":fx"), but the "OK" button is greyed out in the "DeepL Parameters" dialogue

**Comment by berndmoos** [comment]
> Wanted to play with DeepL, got a free DeepL account and an API key (ending in ":fx"), but the "OK" button is greyed out in the "DeepL Parameters" dialogue

@sarkipo : Have you hit <ENTER> after pasting the API key into the text field?

**Comment by sarkipo** [comment]
@berndmoos Oh, thanks! No, just Tab. Now it's activated!

**Comment by berndmoos** [comment]
No reason not to close this, or is there?

**Comment by berndmoos** [comment]
Bug: When "Whole segment chain" is selected, the tranlsation of the second bit also contains the translation of the first bit, the third one of the first and second, and so on.

**Comment by berndmoos** [comment]
![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/877c739c-b5f6-4337-b48b-89addbb984ea)
