### ISSUE TITLE
Punctuation gets lost in generic segmentation for ISO/TEI

### ISSUE THREAD

**Issue by hannahedeland** [EXMARaLDA/exmaralda#308]
The real generic segmentation with `<seg>`s of `@type` `contribution` containg `<w>` and `<pc>` is a part of the WebLicht workflow. It loses punctuation (`<pc>`) at the end of sentences/utterances/...

**Comment by berndmoos** [comment]
Probably a missing rule in /org/exmaralda/tei/xml/SegmentChain2ISOTEIUtterance.xsl

**Comment by berndmoos** [comment]
Fixed that in /org/exmaralda/tei/xml/SegmentChain2ISOTEIUtterance.xsl (with comments at the respective position)
