### ISSUE TITLE
Partitur Editor under Linux cannot open files with media tracks

### ISSUE THREAD

**Issue by bredereck** [EXMARaLDA/exmaralda#326]
Editor always freezes showing "computing width", not matter which version I tried or media backend is used.

I guess this must be somehow a known bug. Any hint or common workaround/debugging?

**Comment by berndmoos** [comment]
Sorry, no working Linux distribution at the moment, we‘re taking a break: https://exmaralda.org/de/2022/06/29/betriebsferien/

**Comment by berndmoos** [comment]
As far as tested, players now work with Linux distributions
