### ISSUE TITLE
export from Elan to exmaralda

### ISSUE THREAD

**Issue by mapeodeldialogo** [EXMARaLDA/exmaralda#327]
I am starting with exmaralda. Now, I am working with Elan, and I'd like to export a eaf file with the media to exmaralda. 

How can I do it?
Thanks

**Comment by berndmoos** [comment]
> I am starting with exmaralda. Now, I am working with Elan, and I'd like to export a eaf file with the media to exmaralda.
> 
> How can I do it? Thanks

Save your transcript as EAF in ELAN, then import it into the Partitur-Editor via File > Import… You may have to reassign the media file and/or adjust settings for the player

**Comment by mapeodeldialogo** [comment]
> 

Thanks
