### ISSUE TITLE
Make annotated FLN usable for EXAKT

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#328]
Probably best by extending the FOLKER import wizard. Building blocks are already there in the ISO/TEI --> EXB conversion.

**Comment by berndmoos** [comment]
First step: direct conversion of FLN to EXS. Takes very long (about 2 minutes for a 30 minutes FLN transcript), but so what?

**Comment by berndmoos** [comment]
Note to @berndmoos : I probably forgot to take care of `<uncertain>`. I do not love `<uncertain>`.

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/208287191-ea7e2427-2549-4c2d-853c-6e83de8b80b9.png)

**Comment by berndmoos** [comment]
To do:
* check `<uncertain>`
* check if displaying additional annotations in additional column works (e.g. for lemma and pos). Rather not...

**Comment by berndmoos** [comment]
Fixed some errors: 

- "norm" and "n" were confounded so that nothing could be found on "norm" annotations
- when the option "Write Basic Transcriptions" was selected, there would be null pointer at some point in the wizard
- the FLN to EXS conversion had to take into account a change for speakerless tiers

Now successfully tested on MEND corpus.

**Comment by berndmoos** [comment]
> displaying additional annotations in additional column works (e.g. for lemma and pos). Rather not...

This is issue #36 .

And this a comment on the fix:

![image](https://user-images.githubusercontent.com/13796493/219963450-68dce373-c53a-4caa-a17c-f4bd05e09c6c.png)

**Comment by philippcirk** [comment]
Error report when I try to generate a FOLKER corpus in EXAKT. Not sure whether the error is related to this issue or more related to OrthoNormal.
![Fehlermeldung_FLNs to Exakt](https://user-images.githubusercontent.com/126662328/222097973-c5d56219-ac94-4605-95c5-cf56120fe13b.png)

**Comment by berndmoos** [comment]
Thanks -- that will be a smaller error in one of the stylesheets, I will just have to find out where. My guess is that this is the word "ruhrpottdeutsch" with a time anchor in the middle. I will try to reproduce with that assumption...

**Comment by berndmoos** [comment]
Reproduced and fixed this one, but noticed now that all annotations are inserted *twice* into the segmented transcription.

**Comment by berndmoos** [comment]
Fixed that one, too, new (Windows) preview underway.

**Comment by berndmoos** [comment]
Let's leave it at that until further notice
