### ISSUE TITLE
Pretty print XML outputs

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#340]
Would make line-wise diffing, especially in git and other VCS, easier. Should be consistent across the tools, so needs a bit of thought. This is a request by INEL (for exb) and AGD (for fln).

**Comment by hhelmer** [comment]
As for the formatting: one element per line would be great!

**Comment by berndmoos** [comment]
Should also make sense for TEI output, so did that.

**Comment by berndmoos** [comment]
@hhelmer: new preview for Windows is at https://exmaralda.org/files/prevDL/experimental.html

**Comment by berndmoos** [comment]
This has introduced a non-trivial bug: JDOM's pretty printing will, by default, trim whitespace also in text content. This is bad for all mixed content and wherever trailing space has a meaning, especially for EXB files in the Partitur-Editor. Fixed this right away, distributed only as "experimental".

**Comment by berndmoos** [comment]
Another non-trivial bug. In FLN, pretty printing will write words with a timestamp like this:

```
<w>
     inter
     <time/>
     rupt
</w>
```

This would lead to a space being appended to the first part of the word, which is bad. The same problem occurs with unparsed contributions on parse-level 1. 
Hopefully fixed this in https://github.com/Exmaralda-Org/exmaralda/commit/9d42acec01c7d81882b07eff4aca5de8de1c78ac with one simple and one rather complicated additional rule in the stylesheet which transforms FLK/FLN to EXB.

**Comment by sarkipo** [comment]
In coma, the indentation is fine but there appear double empty lines between each two lines:
```
<?xml version="1.0" encoding="UTF-8"?>
<Corpus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Id="IDFBD0F3B1-B4E6-E562-1778-9E9860F87078" Name="INEL Kamas Corpus" uniqueSpeakerDistinction="//speaker/abbreviation" xsi:noNamespaceSchemaLocation="http://www.exmaralda.org/xml/comacorpus.xsd">
  
   
  <DBNode />
  
   
  <CorpusData>
    
      
    <Communication Id="CID7C1B65DD-CA06-3FFF-062A-A632310F37B8" Name="AA_1914_Brothers_flk">
      
         
      <Setting>
```
etc.

**Comment by berndmoos** [comment]
Another problem with white-space, this time in OrthoNormal:

![image](https://user-images.githubusercontent.com/13796493/222119038-0121ff18-7bd6-4980-a9fe-ddaf3f3ac228.png)

Pretty printing is causing a lot of trouble wrt to mixed content. Maybe we shouldn't pretty print after all?

**Comment by berndmoos** [comment]
Yet another one: XSLs transforming parsed to unparsed text data also have to be adapted to ignore whitespace inside `<w>`

**Comment by berndmoos** [comment]
Pretty printing can break existing workflows which rely on ugly-print (e.g. FOLK > DGD).

To recapitulate:
- all tools should be able to correctly **read** pretty-printed XML because it is not forbidden to pretty print it
- all tools can be enabled to **write** pretty-printed XML, this is a benefit for some workflows, a problem for others
- the necessary adaptations will be different according to whether the tool reads a DOM or not:
   - CoMa and OrthoNormal work on the DOM
   - Partitur-Editor, FOLKER and EXAKT read XML into custom data structures (i.e. not DOM)

The best solution is probably to make writing pretty-printed XML optional. At least for the transition, not pretty-printing should remain the default solution.

**Comment by berndmoos** [comment]
Nothing more to do here. Or is there?

**Comment by berndmoos** [comment]
Check where empty COMA lines come from and make them go away
