### ISSUE TITLE
MAC Glitches

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#344]
### COMA

- In the COMA Menu, COMA is called "Launcher", i.e. "About Launcher", "Quit Launcher" etc.
- Double-clicking a COMA file will open COMA, but not the file
- COMA files do not have a COMA document icon

### FOLKER
- In the FOLKER Menu, FOLKER is called "ApplicationFrame", i.e. "About ApplicationFrame", "Quit ApplicationFrame" etc.

### OrthoNormal
- In the OrthoNormal Menu, OrthoNormal is called "ApplicationFrame", i.e. "About ApplicationFrame", "Quit ApplicationFrame" etc.

**Comment by Herrner** [comment]
### Installers (all apps)
- The installation volumes (mounted `.dmg`s use the app icons instead of volume icons, and the volume has the name of the application
- The drop target for the apps is called `/Applications`

**Comment by berndmoos** [comment]
see here: https://docs.oracle.com/en/java/javase/16/jpackage/override-jpackage-resources.html#GUID-405708DC-0243-49FC-84D9-B2A7F0A011A9

**Comment by berndmoos** [comment]
<img width="102" alt="image" src="https://user-images.githubusercontent.com/13796493/201146204-9488fe91-0257-437c-b3b7-d53f3fc271d7.png">

<img width="529" alt="image" src="https://user-images.githubusercontent.com/13796493/201146530-c7ef04b8-d3c6-49d4-8b8b-584b5a6f1970.png">

**Comment by berndmoos** [comment]
Build time needs to be updated individually for each bleedin' system

**Comment by berndmoos** [comment]
Misssion accomplished?

* "About" names are correct
* DMGs have icons for mounted volumes
* DMGs also have background images
* Build time is registered individually for each tool

No, not quite:
* file assocs need to be different on M1 so that COMA gets a document icon :-/

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/201277971-f8c843d9-7efa-4d65-87e4-3a5258576489.png)

But double click on a file will still only open COMA, not the file. Make this a new issue: #346

**Comment by berndmoos** [comment]
Closing soon. Any comments anybody? 

@Herrner : dmg backgrounds and dmg volume icons are now all correctly named in https://github.com/Exmaralda-Org/exmaralda/tree/master/src/build/mac/icons. We can change them or leave them as they are...

**Comment by Herrner** [comment]
I'm gonna make a new background image.

**Comment by berndmoos** [comment]
N.B.: It would also be possible, to pack all tools into one distribution, using "launchers". What would that look like??

**Comment by Herrner** [comment]
Would we still have one VM per tool?

**Comment by Herrner** [comment]
> N.B.: It would also be possible, to pack all tools into one distribution, using "launchers". What would that look like??

Like we had it once: 
![Preview](https://user-images.githubusercontent.com/2045460/201430293-6a044b32-d479-48e5-b159-81e62a288135.jpg)

**Comment by berndmoos** [comment]
yea, in ye goode aulde dayze

**Comment by berndmoos** [comment]
and no, the same vm for all tools tha‘s goo‘ innit?

**Comment by berndmoos** [comment]
This background image ain't wide enough for the both of them: 

![image](https://user-images.githubusercontent.com/13796493/201473858-340c975f-f15f-43c0-8b48-184489a9f150.png)

**Comment by Herrner** [comment]
> This background image ain't wide enough for the both of them:

I'm on it...

**Comment by berndmoos** [comment]
https://www.youtube.com/watch?v=Sc55XJ8rjQ0

![image](https://user-images.githubusercontent.com/13796493/203413815-3acddf90-dd3f-4739-9887-a45df35ff6a8.png)

**Comment by Herrner** [comment]
Almost there... not weak yet!

**Comment by berndmoos** [comment]
@Herrner : Am I waiting for something or not?

**Comment by Herrner** [comment]
you are! I'll get to it tomorrow.

**Comment by berndmoos** [comment]
https://www.youtube.com/watch?v=k2rAtuYGT_k

**Comment by berndmoos** [comment]
@Herrner : Go weak now?

![image](https://user-images.githubusercontent.com/13796493/205433733-be90a269-34f3-46d0-94e8-fc7f95b47cd7.png)

**Comment by Herrner** [comment]
Not really... I'm gonna change them again, but that should not stop you from releasing anything...

**Comment by berndmoos** [comment]
Caloze
