### ISSUE TITLE
Confusion in the launchery

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#349]
@Herrner : what is the difference between `org.exmaralda.coma.launch.ComaLauncher` and `org.exmaralda.coma.launcher.Launcher` ??

**Comment by Herrner** [comment]
`¯\_(ツ)_/¯`

I'll have to look into this. Are they both used? I guess there's still unused code hanging around...

**Comment by berndmoos** [comment]
I have been using org.exmaralda.coma.launcher.Launcher for quite some time. The other one works, too (as a launcher), and the code is mostly identical. Thwow it away?

**Comment by Herrner** [comment]
Be my guest!

**Comment by berndmoos** [comment]
It has be thwon out of the window.
