### ISSUE TITLE
Corpus wizard needs option to set custom FSM

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#359]

**Comment by Herrner** [comment]
😱

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/213708947-3f3b1345-4fe1-4493-8c31-d8519d36c8a9.png)

**Comment by berndmoos** [comment]
???

![image](https://user-images.githubusercontent.com/13796493/213710156-bcbbb7e1-cf35-4451-b170-11055b942a92.png)

**Comment by berndmoos** [comment]
?????!!!!!

![image](https://user-images.githubusercontent.com/13796493/213712423-cb3026a8-ad3d-489c-b7d2-76ce980052d4.png)

**Comment by berndmoos** [comment]
Done for now.

**Comment by berndmoos** [comment]
Hey, I said "done for now"!
