### ISSUE TITLE
Dialog Window: Select audio or video recording

### ISSUE THREAD

**Issue by wuddel** [EXMARaLDA/exmaralda#371]
In the Partitur-Editor (not FOLKER) on Windows 10 (not Linux), the "open" and "cancel" Buttons are not fully visible, cf.:
![grafik](https://user-images.githubusercontent.com/58472461/219376847-9d381cc5-e8e9-4355-aa80-ad12cf2615ff.png)
When the dialog box initially pops up, the two buttons are visible for a fraction of a second, and then look like in the image.
My build is from 2023_02_07 (9 days ago).

**Comment by berndmoos** [comment]
Not chez moi (Windows 11) I'm afraid. And I am doing nothing in the code to set the size of that dialog. There are issues in other dialogues where the preferred size is set to fit ancient screen sizes/resolutions (#218), but I am not doing that here. Maybe try on Windows 11... In any case, you can make the buttons reappear by dragging the lower right corner of the dialog. 

![image](https://user-images.githubusercontent.com/13796493/219871744-898edb62-3003-485d-8560-20012de30b21.png)

**Comment by berndmoos** [comment]
Closing this, not really reproducible and watched over in #218
