### ISSUE TITLE
List events view

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#382]
As in "Tier > List events..." to display in a vertical list all events from the currently selected tier. This is a non-modal dialog, so double-clicking can be used to navigate in the Partitur. This was there already (July 22?), but I couldn't find an issue for it. 

Now the thing is: make this a table rather than a list. So that we can display start and end times, and we can sort. Later on, maybe add a button for "add(ing)" corresponding (annotation) tiers and make the table editable. Then we could have an editing mode for events and their annotations (for example: transcription and utterances side-by-side).

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/233839752-c548059e-fe26-4ef7-b1cd-4dc2eb7491c2.png)

**Comment by berndmoos** [comment]
Now pretty and editable:

![image](https://user-images.githubusercontent.com/13796493/236627127-f2544a34-02bc-4726-a46d-d9439e6383c1.png)

**Comment by Herrner** [comment]
Color advisor here... Could you make the green _much_ darker?

**Comment by berndmoos** [comment]
Color man! It is you! Sure, I can do `Color.green.darker().darker()`

![image](https://user-images.githubusercontent.com/13796493/236700689-e42cf9f2-80cc-4e18-b8f7-76f71831e673.png)

**Comment by Herrner** [comment]
You want it darker, we kill the flame.

**Comment by berndmoos** [comment]
We want this in the context menu for tiers.

**Comment by berndmoos** [comment]
![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/9f829144-dc4c-456b-a90e-9202e430b9b6)
