### ISSUE TITLE
Delete several events in one go

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#389]
(Suggested by INEL)

**Comment by berndmoos** [comment]
Basic functionality is there.

**Comment by berndmoos** [comment]
@git-debase-verbose and @lena-laz : I don't want this to have the same icon as "Remove event". Can you simply remove the icon from the action?

**Comment by sarkipo** [comment]
@berndmoos 
Just installed the fresh preview but the version info says it's from May 22, and I don't find the new command...)

**Comment by sarkipo** [comment]
Great, it's working! I found it.
(just the build date in the "About..." window was wrong)

**Comment by sarkipo** [comment]
Could you please make it also work for vertical selections like this:
![image](https://github.com/Exmaralda-Org/exmaralda/assets/11090777/1df4fa1c-fa3d-4094-a3e2-50cd5245ff69)
It is greyed out in the menu if the selection is only one event wide

**Comment by sarkipo** [comment]
And the undo worked perfectly for several deletes in a row! :)

**Comment by sarkipo** [comment]
It works! :-)
