### ISSUE TITLE
Formatting is lost after some actions

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#397]
- changing show/hide in Edit tiers menu resets formatting
- Undo after removing tiers resets formatting

**Comment by berndmoos** [comment]
See also #398

**Comment by berndmoos** [comment]
Did something about it, first tests were okay. @sarkipo : can you check the latest preview one of these days?

**Comment by sarkipo** [comment]
@berndmoos Yep, Undo remove tier and changing show/hide in Edit tiers did work properly and did not ruin the formatting!
