### ISSUE TITLE
Saving format table should be default

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#398]

**Comment by berndmoos** [comment]
See also #397

**Comment by sarkipo** [comment]
For me the "Save formats" checkbox in Save As is still disabled by default, and hitting the Save button did lose the formatting. (New release)

**Comment by berndmoos** [comment]
True: the attribute is not taken care of when opening via double click or via recent files. Changing this.

**Comment by sarkipo** [comment]
Will that also work when hitting Ctrl+S ?

**Comment by berndmoos** [comment]
> Will that also work when hitting Ctrl+S ?

It should -- "File > Save" checks if a format table is present. If yes, it will be saved. If it hasn't worked before, then probably because the file was opened via recent files or double click, and the presence of a format table was not detected. That's what changed now.
