### ISSUE TITLE
Change default logging directory

### ISSUE THREAD

**Issue by Herrner** [EXMARaLDA/exmaralda#400]
The EXMARaLDA-Tools seem to be the only tools that log into the first level of the user directory, which kind of sucks. 
Since they probably all use a logging library, couldn't we just let them log to default directories (like `/var/log` on Linux/MacOS and `hell/knows/where` on Windows)?

**Comment by Herrner** [comment]
Oh. The logging library is [our own](https://github.com/Exmaralda-Org/exmaralda/blob/master/src/org/exmaralda/common/Logger.java). This changes things, since you usually can't write to the default logging directories. Oh well.

**Comment by berndmoos** [comment]
The loggin directory can be changed:

![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/a505158d-ba06-4b9e-b911-4a24c62725e9)

Also, I could try to set a better directory as the default. Will do. 

> The logging library is [our own](https://github.com/Exmaralda-Org/exmaralda/blob/master/src/org/exmaralda/common/Logger.java).

"Library"! Ahahaha!

**Comment by Herrner** [comment]
It's a good thing that our "Library" exists, so one /could/ change logging for all tools by plugging log4j or whatnot into this.

**Comment by berndmoos** [comment]
Nuttin' left to do here
