### ISSUE TITLE
Maintain Praat panel functionality

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#401]
Does not seem to be working any longer -- see error message. Also, sendpraat.exe is now officially sendpraat-win.exe. Needs maintenance...

![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/e6121b08-77bc-404f-b229-7aa3f9ef420a)

**Comment by berndmoos** [comment]
https://groups.io/g/Praat-Users-List/topics

**Comment by sarkipo** [comment]
Paul Boersma will be giving a plenary for the 30th anniversary of Praat at the phonetic congress in August, will try to ask him about that if he doesn't reply to the list

**Comment by berndmoos** [comment]
I had a reply off-list. The problem is probably not the Praat commands, but that the way Java is calling external processes has changed.

**Comment by berndmoos** [comment]
May have fixed that. Should re-check #44 one of these days.

**Comment by berndmoos** [comment]
> "Ich habe mir EXMARaLDA neu runtergeladen und das Praat-Panel klappt einwandfrei. "
