### ISSUE TITLE
New from Dulko template

### ISSUE THREAD

**Issue by nolda** [EXMARaLDA/exmaralda#405]
In the former, [stand-alone edition of the Dulko tools](https://sr.ht/~nolda/exmaralda-dulko/), the [Dulko template](https://hg.sr.ht/~nolda/exmaralda-dulko/browse/dulko.template.exb) was a regular file in the installation directory and thus could be opened by the user. Since the integration of the Dulko tools into EXMARaLDA, the [Dulko template](https://github.com/Exmaralda-Org/exmaralda/blob/master/src/org/exmaralda/dulko/resources/dulko-template.exb) is an internal part of EXMARaLDA and no longer easily accessible by the user.
It would thus be nice to have a menu entry in the File menu ("New from Dulko template …") for opening the Dulko template (unmodified, without any parameter settings).

**Comment by berndmoos** [comment]
It's there. Can you check if the template is up-to-date/general enough? I am wondering, for instance, whether we will want "University of Szeged" in there.

**Comment by nolda** [comment]
Cf. PR #406.
