### ISSUE TITLE
Error when opening transcripts in FOLKER

### ISSUE THREAD

**Issue by philippcirk** [EXMARaLDA/exmaralda#414]
FOLKER shows the following error when trying to reopen a transcript after saving. 
Might be relevant information: the primary transcript was created with whisper, imported as an srt-file to FOLKER and had been adjusted manually for the most part until to the error message showed up. 
<img width="958" alt="error message_FOLKER_1" src="https://github.com/Exmaralda-Org/exmaralda/assets/126662328/17e48e35-0ea3-40f0-a880-362578b7ba01">

**Comment by berndmoos** [comment]
Looks like a corrupt XML to me, i.e. nothing to do with SRT. @philippcirk : Can you send the file in question to my personal e-mail?

**Comment by berndmoos** [comment]
Not a bug, file was corrupt
