### ISSUE TITLE
Undocumented commands in PE

### ISSUE THREAD

**Issue by sarkipo** [EXMARaLDA/exmaralda#415]
What does Timeline > Anchor timeline do?

And what should be the effect of the button 
![grafik](https://github.com/Exmaralda-Org/exmaralda/assets/11090777/ecd9e0a9-e084-4920-b376-d9152d163116)
"Switch playback mode on/off"?

(Actually I was looking for a way to specify a time offset for the video (different from the audio) but haven't found any. Might be a separate issue)

**Comment by berndmoos** [comment]
Documentation has been neglected for quite some time, and I don't see that I can find the resources to change this soon. 

"Playback mode" will make the Partitur scroll in sync with the position in the recording and highlight the current position (switch on, press play). 

"Anchor timeline" will assign 0.0 to the first TLI and the duration of the recording to the last TLI when/if the timeline has no absolute time values (yet)

You cannot use different time offsets for different media. The assumption is that all media files are synced (better anyway for corpus management). Cut or add something to the audio or video file, you can shift absoulte times via "Timeline > Modify absolute times"

**Comment by sarkipo** [comment]
Clear, thanks!

>>The assumption is that all media files are synced (better anyway for corpus management).
Well, sure)  But that's not always the way they're created)  (in this case we had a camcorder and a sound recorder, and each was started by hand i.e. necessarily with some lag). Will chop off/add something then.
