### ISSUE TITLE
citation info

### ISSUE THREAD

**Issue by agricolamz** [EXMARaLDA/exmaralda#429]
Hello, thank you for your work. I'd like to suggest to add citation info to github repo and to the about part of Exmaralda program.

Cheers

**Comment by berndmoos** [comment]
Thanks for the feedback and for the suggestion. We'll do that :-)

**Comment by Herrner** [comment]
https://github.com/citation-file-format/citation-file-format

**Comment by berndmoos** [comment]
<img width="401" alt="image" src="https://github.com/Exmaralda-Org/exmaralda/assets/13796493/92f79294-b89b-48d8-b4f4-70c250221d17">

**Comment by berndmoos** [comment]
<img width="406" alt="image" src="https://github.com/Exmaralda-Org/exmaralda/assets/13796493/d7833f37-e7df-4df6-9651-0dc5427611ac">

**Comment by berndmoos** [comment]
Dunnit

**Comment by agricolamz** [comment]
Good, thank you!
