### ISSUE TITLE
Retire / Move TexGUT

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#449]
The functionality goes into web services in the TGDP ZuMult instance. No need to maintain in inside EXMARaLDA. Needs to go also from the build scripts.

**Comment by berndmoos** [comment]
It's gone. It is dead. Deceased. It has gone to meet its maker. It is pushing up the daisies.

**Comment by Herrner** [comment]
Did it kick the bucket, too?

**Comment by berndmoos** [comment]
Yes, it is no more. It has bitten the bullet.
