### ISSUE TITLE
Give editing cell a prominent visual marker

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#458]
.. as it is, it is a bit hard to detect...

**Comment by berndmoos** [comment]
![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/48799715-c938-411a-a592-6b3eca938e6d)
 
Better?

**Comment by Herrner** [comment]
Better, yes. But why not make the border all around? Spreadsheet for example always have a full border around the cell being edited.

**Comment by berndmoos** [comment]
The fatter, the better...

**Comment by berndmoos** [comment]
Let's call this fat enuff.

![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/ac809338-4567-45a6-8a47-bfcffbef4d05)
