### ISSUE TITLE
Interoperability with noScribe

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#463]
Related to #357 and #119. Also related to https://github.com/kaixxx/noScribe/issues/25. Need example material.

**Comment by kaixxx** [comment]
Updates: https://github.com/kaixxx/noScribe/issues/25#issuecomment-2103005187

**Comment by berndmoos** [comment]
Import will work via VTT, so this is related to #119

**Comment by berndmoos** [comment]
Convenience for assigning media:

![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/8de473e5-3d81-45d6-9096-efca9fa605e2)
