### ISSUE TITLE
Collect types for an entire corpus

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#475]
See #295

**Comment by berndmoos** [comment]
This requires collecting category/type combinations for tiers first:

![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/c5fcbadc-7fb9-45e5-9010-42b0a3be1d01)

**Comment by berndmoos** [comment]
![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/c42636c7-c475-4f21-b88c-6824b03490c5)

![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/ad07be57-4a17-475c-9c7f-1947718fa38f)

![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/c096957c-c89c-44fb-a252-ce76dea63cd0)

**Comment by berndmoos** [comment]
Sadly (?), this would also make a lot of sense in EXAKT...

**Comment by sarkipo** [comment]
Wow, that's great!
Does the "Map to" in coma have any effect yet?

**Comment by berndmoos** [comment]
> Does the "Map to" in coma have any effect yet?

No, it doesn't. I can add this, it would just need a prominent "ARE YOU REALLY SURE?" before it is carried out.

**Comment by berndmoos** [comment]
Now it does:

![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/3de8b9f3-2ec4-4014-9ec0-130462fc65a5)

![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/a86a02cf-9fa2-49ea-abea-b35af432988b)

![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/c2041419-298c-46d1-8189-6350d6536a6a)

**Comment by berndmoos** [comment]
Daring to close

**Comment by berndmoos** [comment]
Continuing this in #512
