### ISSUE TITLE
The org.exmaralda.pro.* package

### ISSUE THREAD

**Issue by git-debase-verbose** [EXMARaLDA/exmaralda#476]
I updated the local copy of the repository earlier today, and the code does not compile anymore because the titular package does not exist on my machine. Based on the naming I assume it is supposed to be included in the repository, which is not the case for some reason.

Would it be possible to do something about it?

**Comment by berndmoos** [comment]
The quick and dirty way would be to include exmaraldapro_nb.jar in your classpath. On Windows, you will find it under C:\Program Files\EXMARaLDA\app\lib. Less quick and dirty would be to give you access to my private GitHub repo with the code. I'd have to check for secrets first, though.

**Comment by git-debase-verbose** [comment]
Thanks, the quick and dirty method worked.

**Comment by berndmoos** [comment]
Closing for now. The least quick and dirty way would be to have the "main" code only talk to an interface. Might do that later.
